#ifndef WAVELET_KERNEL_GENERATOR_TYPES_H
#define WAVELET_KERNEL_GENERATOR_TYPES_H
#include <string>

enum wavelet_optim_warp
{
	WAVELET_OPTIM_WARP_NONE = 0,
	WAVELET_OPTIM_WARP_LOCAL,
	WAVELET_OPTIM_WARP_SHUFFLE
};

struct s_wavelet_type_info
{
	float *coef;
	float norm;
	unsigned int steps;
	unsigned int width;
	std::string define;
};

enum e_intrinsics
{
	INTRINSICS_NONE,
	INTRINSICS_SSE,
	INTRINSICS_AVX,
	INTRINSICS_AVX512
};

enum e_kernel_type
{
	WAVELET_KERNEL_OTHER = 0,
	WAVELET_KERNEL_SWELDENS,
	WAVELET_KERNEL_IWAHASHI,
	WAVELET_KERNEL_EXPLOSIVE,
	WAVELET_KERNEL_MONOLITHIC,
	WAVELET_KERNEL_POLYPHASE,
	WAVELET_KERNEL_CONVOLUTION,
	WAVELET_KERNEL_POLYPHASE_SEP_NONE,
	WAVELET_KERNEL_POLYPHASE_SEP_HOR,
	WAVELET_KERNEL_POLYPHASE_SEP_VERT,
	WAVELET_KERNEL_POLYPHASE_SEP_ALL,
	WAVELET_KERNEL_CONVOLUTION_SEP_NONE,
	WAVELET_KERNEL_CONVOLUTION_SEP_HOR,
	WAVELET_KERNEL_CONVOLUTION_SEP_VERT,
	WAVELET_KERNEL_CONVOLUTION_SEP_ALL
};
#endif